enum ApiKey {
  auth = 'auth',
  me = 'me',
  nonce = 'nonce',
  verify = 'verify',
  logout = 'logout',
  squads = 'squads',
  joinOpen = 'join-open',
  leave = 'leave',
  heatmap = 'heatmap',
  leaderboard = 'leaderboard',
  day = '24hr',
  total = 'total',
  my = 'my',
  list = 'list',
  page = 'page',
  orderBy = 'order_by',
  wallet = 'wallet',
  alias = 'alias',
  insight = 'insight',
  token = 'token',
  frontline = 'frontline',
  rankings = 'rankings',
  squad = 'squad',
  ranking = 'ranking',
}

export default ApiKey;
